# Generated by Django 5.1.2 on 2024-10-10 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_transactiongroup_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.transactiongroup",
            ),
        ),
    ]
