# Generated by Django 5.1.2 on 2024-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_transaction_options_transaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="title",
            field=models.CharField(default="Shared Transaction", max_length=64),
        ),
    ]
