# Generated by Django 5.1.2 on 2024-10-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_transaction_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionshare",
            name="amount",
        ),
        migrations.AddField(
            model_name="transactionshare",
            name="amount_owed",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactionshare",
            name="amount_paid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
