# Generated by Django 5.1.2 on 2024-10-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_transactionshare_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_internal_payment",
            field=models.BooleanField(default=False),
        ),
    ]
